### PR TITLE
Remove select2-rails and upgrade to select2 4.0.7

### LINKED ISSUE #263: select2-rails is no longer maintained
I have been trying to work with the author of select2-rails to integrate a more recent version for over a year with no reply. It appears that the project is unmaintained. See https://github.com/argerim/select2-rails/issues/175 or look at the numerous PRs for upgrades that have not been looked at in 18 months: https://github.com/argerim/select2-rails/pulls

Because activeadmin_addons uses select2-rails as a dependency, we are stuck with version 4.0.3 (the latest published by select2-rails). However, 4.0.3 introduced an annoying bug which means that users can't tab through select fields with the tab key. This is the source of https://github.com/platanus/activeadmin_addons/issues/248. This bug affects me as well, and it was fixed in 4.0.4. See https://github.com/select2/select2/releases/tag/4.0.4

I think it would be smart for this project to vendor the select2 assets directly and stop relying on select2-rails, which is unmaintained and on an old version. Select2 is now up to 4.0.7, and it would be great to bring these changes in.

### PR DESCRIPTION
**Pull request by mattolson**
* select2-rails is no longer supported, so we will vendor the files directly
* Bring in latest version of select2 (4.0.7). These files were pulled from the dist folder of https://github.com/select2/select2/archive/4.0.7.zip
* Add vendor/bundle to .gitignore for convenience locally
* Update db/schema for test db due to recent formatting changes in ActiveRecord (no substantive changes)

Fixes #263

### CODE REVIEW

**Comment by mattolson** [comment]
There seems to be an issue with the test suite. I'm getting the following errors in Travis.
```
Selenium::WebDriver::Error::SessionNotCreatedError:
        session not created: Chrome version must be between 70 and 73
          (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Linux 4.4.0-101-generic x86_64)```

I see that other recent PRs have the same issue. I will attempt to address in a separate PR.

**Comment by mattolson** [comment]
Test suite has been fixed via #265. I'll rebase once that is merged.

**Comment by rjherrera** [comment]
Hi @mattolson! could you rebase this PR so that the CI build passes and we can review your changes? Thank you!

**Comment by mattolson** [comment]
@rjherrera Ok, I've rebased on master. Sorry for the delay.

**Comment by jgmontoya** [comment]
Hi!
I want to push this forward.

It's been quite some time since the PR was opened (sorry about that :pray:) and now select2 latest version is 4.0.13. Several bugs have been squashed between versions 4.0.7 and 4.0.13 so I think we should use the latter, it should be a pretty straight-forward change though.

I'm pinging @ldlsegovia to get his take on this.

**Comment by ldlsegovia** [comment]
> Hi!
> I want to push this forward.
> 
> It's been quite some time since the PR was opened (sorry about that 🙏) and now select2 latest version is 4.0.13. Several bugs have been squashed between versions 4.0.7 and 4.0.13 so I think we should use the latter, it should be a pretty straight-forward change though.
> 
> I'm pinging @ldlsegovia to get his take on this.

Thank you @mattolson! I think we can do the update :)

**Pull request merged**
