### PR TITLE
fix(): change syntax to play nice with ruby v2.1.2

### PR DESCRIPTION
**Pull request by ldlsegovia**
closes #192

### CODE REVIEW

**Comment by sairam** [comment]
@ldlsegovia , should we add ruby 2.1 dep on travis as well?

**Comment by ldlsegovia** [comment]
@sairam No. I don't want to add support for v2.1. I made the fix hoping it will not break if someone has that version.

**Comment by sairam** [comment]
makes sense. We are on 2.1 and got this failure on CI when depfu bot upgraded this. I assumed, you did not support 2.1 and raised a PR for 2.2. 
May I know when the next release is expected to be?

**Comment by ldlsegovia** [comment]
I've just made a release https://rubygems.org/gems/activeadmin_addons/versions/1.3.0
and we are testing these versions https://github.com/platanus/activeadmin_addons/blob/master/.travis.yml#L4

**Pull request merged**
