### PR TITLE
Make sprockets dependency optional

### PR DESCRIPTION
**Pull request by joker-777**
It looks like sprockets will be soon replaced by propshaft. It would be great if we could make the sprockets dependency optional. (https://github.com/platanus/activeadmin_addons/issues/403)

### CODE REVIEW

**Comment by gap777** [comment]
@ldlsegovia @GabrielLyonB et al... this PR removes a dependency upon `sassc-rails`, which happens to also make it compatible with Rails 7 + css-bundler (tailwind) + js-bundler (esbuild), which we need in order to use your awesome `activeadmin_addons` package. 

Could you approve this and merge it in?

**Comment by joker-777** [comment]
Sorry, I just realized that I created the PR based on my master branch where I pushed lots of other changes I need for my project. Unfortunately, it seems that `activeadmin_addons` isn't maintained anymore :(

**Comment by joker-777** [comment]
Thanks, maybe I will create another PR but I doubt that there is anyone maintaining this repository.

**Comment by ldlsegovia** [comment]
@joker-777 We're still alive, thankfully :) Creating a new PR with the sprockets related changes sounds good.

**Comment by joker-777** [comment]
@ldlsegovia This is good news!!! I will try to create a new PR then.

Can you also have a look at my other PRs, please?
https://github.com/platanus/activeadmin_addons/pull/419
https://github.com/platanus/activeadmin_addons/pull/423

**Comment by difernandez** [comment]
Hi all, sorry for the late comment. Wanted to let you know that we are planning a beta release for a new major version of this gem, which will drop support for sprockets, among other things. Theses changes will include the removal of sassc and sassc-rails dependencies. We’ll leave the related issues open for now, at least until the release of this version, but will be closing related PRs, as we might need to include similar changes in the removal of sprockets support.

**Pull request closed without merging**
