### PR TITLE
remove active_material from dependency (break changes)

### PR DESCRIPTION
**Pull request by cprodhomme**
i don't use `active_material` and i think it's sad to implement this gem for no reason

infortunatly, this is a break changes

what do you think about this idea ?

### CODE REVIEW

**Comment by cprodhomme** [comment]
need to merge #265 before this

**Comment by rjherrera** [comment]
@cprodhomme I'm not sure if I understood the idea. Are you proposing to remove the gem from the dependencies as it is not used by default, and that we should make the user responsible of including it if needed?

If that's the idea, I like it but, as you say, it's breaking. If we merge this, we should release it in version 2.0

**Comment by fabn** [comment]
+10 for this, lot of other gems follow this pattern. Also the same should be done for `xdan-datetimepicker-rails` dependency.

**Comment by difernandez** [comment]
closing this, as active_material has been removed in v2 beta. [More details here](https://github.com/platanus/activeadmin_addons/releases/tag/v2.0.0.beta.0). Thank you!

**Pull request closed without merging**
